services:
  - type: web
    name: internship-survey-app
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn internship_app.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"