# Generated by Django 5.2.6 on 2025-09-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='favorite_feature',
            field=models.CharField(blank=True, max_length=100, verbose_name="What's your favorite feature?"),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], default='prefer_not', max_length=10),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='improvement_suggestions',
            field=models.TextField(blank=True, verbose_name='Suggestions for improvement'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='price_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='product_usage',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('rarely', 'Rarely'), ('first_time', 'First Time')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='quality_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='support_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='would_recommend',
            field=models.IntegerField(choices=[(1, '1 - Very Unlikely'), (2, '2 - Unlikely'), (3, '3 - Neutral'), (4, '4 - Likely'), (5, '5 - Very Likely')], default=3),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Additional comments'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='satisfaction_score',
            field=models.IntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], default=3),
        ),
    ]
